### ISSUE TITLE
llvm version and other system dependencies

### ISSUE THREAD

**Issue by iskindar** [HongliangLiang/leofuzz#1]
Thank you for open-source this excellent work!

I wonder about the version of llvm and other system dependencies you used in leofuzz.
Since I encountered the following error when using the llvm pass to static analysis.

```
error: unable to load plugin '/workdir/leofuzz/leofuzz/afl-2.52b/afl-llvm-pass.so': '/workdir/leofuzz/leofuzz/afl-2.52b/afl-llvm-pass.so: undefined symbol:
      _ZN4llvm24DisableABIBreakingChecksE'
clang (LLVM option parsing): Unknown command line argument '-outdir=/mjs-issues-78/obj-leofuzz/temp'.  Try: 'clang (LLVM option parsing) -help'
clang (LLVM option parsing): Did you mean '-cppfor=/mjs-issues-78/obj-leofuzz/temp'?
```
I tried the llvm 3.8 and llvm 11, getting the same error report. 
Is the llvm version wrong?

**Comment by HongliangLiang** [comment]
Hi, Iskindar, LLVM version 6.0 is used in Leofuzz.

**Comment by iskindar** [comment]
Thank you for your reply! 
However, it didn't work after I tried the llvm 6.0. Maybe it is caused by other dependency issues.
It will be great if you can provide a docker image of leofuzz.
Anyway, thank you for open-source this work!
